name: legacy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          #- 2.4.6
          #- 2.5.6
          - 2.6.9
          - 2.7.17
          - 3.6.9
          - 3.7.5
          - 3.8.0

    steps:
    - uses: actions/checkout@main
    - name: Install legacy python version
      uses: gabrielfalcao/pyenv-action@v6
      with:
        default: "${{ matrix.python }}"
    - name: Install dependencies
      env: 
        PIP_INDEX_URL: https://pypi.org/simple
      run: |
        pip install -U pip
        pip install -r requirements.txt
        pip install .
    - name: Run tests
      run: |
        python setup.py test
