name: legacy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - 2.4.6
          - 2.5.6
          - 2.6.9

    steps:
    - uses: actions/checkout@main
    - name: Install legacy python version
      uses: gabrielfalcao/pyenv-action@v6
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Run tests
      run: |
        python setup.py test
